cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path("", views.view_cart, name="view_cart"),
    path("add_to_cart/<str:model>", login_required(views.add_to_cart) , name="add_to_cart"),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("phones/", views.get_phone, name = "get_phone"),
    path("phones/insert/", views.insert_phone, name="insert_phone"),
    path("phones/update/<str:model>", views.update_phone, name="update_phone"),
    path("phones/delete/<str:model>", views.delete_phone, name="delete_phone")
]

phone_selling_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required

# from user.views import Login, Register, Profile


urlpatterns = [
    path('admin/', admin.site.urls),
    # home or phones
    path("", include("phones.urls")),
    # user
    path("user/", include("user.urls")),
    # dashboard
    path("dashboard/", include("dashboard.urls")),
    # cart
    path("cart/", include("cart.urls")),
    # order
    path("order/", include("orders.urls")),
    # review
    path("reviews/", include("review.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

phones/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.render_home, name="home"),
    path("detail/<str:model>", views.render_detail, name="detail"),
]

dashboard/models.py
from django.db import models

# Create your models here.

class Phone(models.Model):

    ram_sizes = [
        ("2 gb","2 GB"),
        ("3 gb","3 GB"),
        ("4 gb","4 GB"),
        ("6 gb","6 GB"),
        ("8 gb","8 GB"),
        ("12 gb","12 GB"),
        ("16 gb","16 GB"),
        ("18 gb","18 GB"),
        ("24 gb","24 GB"),
    ]

    storage_sizes = [
        ("8 gb","8 GB"),
        ("16 gb","16 GB"),
        ("32 gb","32 GB"),
        ("64 gb","64 GB"),
        ("128 gb","128 GB"),
        ("256 gb","256 GB"),
        ("512 gb","512 GB"),
        ("1 tb","1 TB"),
        ("2 tb","2 TB"),
    ]

    brand_names = [
            ("iphone", "IPhone"),
            ("samsung", "Samsung"),
            ("oppo", "Oppo"),
            ("vivo", "Vivo"),
            ("infinix", "Infinix"),
            ("redmi", "Redmi"),
            ("one plus", "One plus"),
    ]

    banner = models.ImageField(default="fallback.png", blank=True)
    model_name = models.CharField(max_length=100, primary_key=True)
    brand = models.CharField(
        max_length=50,
        choices = brand_names
    )
    instock = models.IntegerField()
    release_date = models.DateField()
    price = models.FloatField()
    os = models.CharField(max_length=100)
    cpu = models.TextField()
    ram = models.CharField(
        max_length=10,
        choices = ram_sizes
    )
    storage = models.CharField(
        max_length=10,
        choices=storage_sizes
    )
    battery = models.TextField()
    dimension = models.TextField()
    resolution = models.TextField()
    screen = models.TextField()
    network = models.CharField(max_length=100)
    wifi = models.CharField(max_length=100)
    sim_type = models.CharField(max_length=100)
    color = models.CharField(max_length=50)
    
    def __str__(self):
        return self.model_name

phones/models.py
from django.db import models
from django.contrib.auth.models import User
from dashboard.models import Phone

# Create your models here.

class ReviewModel(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.ForeignKey(Phone, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.username} - {self.phone} - {self.created_at}"

dashboard/forms.py
from django import forms 
from .models import Phone

class PhoneForm(forms.ModelForm):

    class Meta:
        model = Phone
        fields = "__all__"
        widgets = {
            "banner" : forms.FileInput(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "model_name" : forms.TextInput(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "brand" : forms.Select(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "instock" : forms.NumberInput(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "price" : forms.NumberInput(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "os" : forms.Textarea(
                attrs = {
                    "class" : "form-control",
                    "rows" : 3,
                    "cols" : 20
                }
            ),
            "cpu" : forms.Textarea(
                attrs = {
                    "class" : "form-control",
                    "rows" : 3,
                    "cols" : 20
                }
            ),
            "ram" : forms.Select(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "storage" : forms.Select(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "battery" : forms.Textarea(
                attrs = {
                    "class" : "form-control",
                    "rows" : 3,
                    "cols" : 20
                }
            ),
            "dimension" : forms.Textarea(
                attrs = {
                    "class" : "form-control",
                    "rows" : 3,
                    "cols" : 20
                }
            ),
            "screen" : forms.Textarea(
                attrs = {
                    "class" : "form-control",
                    "rows" : 3,
                    "cols" : 20
                }
            ),
            "resolution" : forms.Textarea(
                attrs = {
                    "class" : "form-control",
                    "rows" : 3,
                    "cols" : 20
                }
            ),
            "network" : forms.TextInput(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "wifi" : forms.TextInput(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "sim_type" : forms.TextInput(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "color" : forms.TextInput(
                attrs = {
                    "class" : "form-control"
                }
            ),
            "release_date" : forms.DateInput(
                attrs = {
                    "type" : "date",
                    "class" : "form-control"
                }
            )
        }

phones/forms.py
from django import forms 
from .models import ReviewModel

class ReviewForm(forms.ModelForm):

    

    class Meta:
        model = ReviewModel
        fields = ["comment"]
        widgets = {
            "comment" : forms.Textarea(
                attrs = {
                    "class" : "form-control mb-3 border border-2",
                    "placeholder" : "Leave a Write to express your experience",
                    "style" : "resize: none",
                }
            )
        }

dashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import PhoneForm
from .models import Phone

# Create your views here.

# get phones
def get_phone(request):
    phones = Phone.objects.all()
    return render(request, "dashboard/phones/list.html", {"phones" : phones})

# insert phone
def insert_phone(request):
    if request.method == "POST":
        form = PhoneForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("get_phone")
    else:
        form = PhoneForm()
    return render(request, "dashboard/phones/add_form.html", {"form" : form})

# update phone
def update_phone(request, model):
    phone = Phone.objects.get(model_name = model)
    print(phone.banner)
    if request.method == "POST":
        form = PhoneForm(request.POST, request.FILES, instance=phone)
        if form.is_valid():
            form.save()
            return redirect("get_phone")
    else:
        form = PhoneForm(instance=phone)
    return render(request, "dashboard/phones/update_form.html", {"form" : form})

# delete phones
def delete_phone(request, model):
    Phone.objects.filter(model_name=model).delete()
    return redirect("get_phone")

phones/views.py
from django.shortcuts import render
from django.http import HttpResponse
from dashboard.models import Phone
from .forms import ReviewForm
from .models import ReviewModel
from dashboard.decorators import regular_user_required

# Create your views here.

@regular_user_required
def render_home(request):

    phones = Phone.objects.all()[:8]
    latest_phones = Phone.objects.filter().order_by("-release_date")[:8]
    brands = Phone.objects.values_list("brand", flat=True).distinct()

    return render(request, "phones/phone_list.html", {"phones" : phones, "latest_phones" : latest_phones, "brands" : brands})

@regular_user_required
def render_detail(request, model):
    
    phone = Phone.objects.get(model_name=model)
    quantity_range = range(1, phone.instock + 1)
    reviews = ReviewModel.objects.filter(phone = phone).order_by("-created_at")
    form = ReviewForm()

    return render(request, "phones/phone_detail.html", {"phone" : phone, "quantity_range" : quantity_range, "form" :form, "reviews" : reviews})

dashboard/templates/dashboard/phones/add_form.html
{% extends "dashboard/navpane.html" %}
{% load static %}
{% block title %}New Phone{% endblock  %}
{% block content %}
    
    {{ block.super }}

    <div class="bg-white border border-3 border-grey my-5 px-5 py-3 col-auto" style="border-radius:20px">
        <a class="text-dark btn text-decoration-none mt-3 mb-5" href={% url "dashboard:get_phone" %}><i class="fa-solid fa-arrow-left"></i> Back</a>

        <div class="container vw-100">
            <div class="row">
                <form method="POST" enctype="multipart/form-data" class="col-md-8" >
                    <div class="border border-3 border-grey p-4 mb-2" style="border-radius:20px">
                        <h1 class="h2 mb-5">Add Phone and Specifications</h1>
                        {% csrf_token %}
                        {% for each in form %}
                            <div class="form-group mb-3">
                                <label for={{each.id_for_label}} class="form-label" >{{ each.label }}</label>
                                {{ each }}
                            </div>
                        {% endfor %}
                    </div>
                    <button class="btn btn-color w-100 fw-bold py-4" type="Submit" >Add Product</button>
                </form>
                <div class="col-md-2 border border-5 border-dark overflow-hidden" style="width:200px; height: 300px">
                    <img id="image_preview" src={% static "img/fallback.png" %} class="w-100 h-100" style="object-fit:contain" alt="">
                </div>
            </div>
        </div>
    </div>

    <!-- Boostrap CDN JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js" integrity="sha384-7qAoOXltbVP82dhxHAUje59V5r2YsVfBafyUDxEdApLPmcdhBPg1DKg1ERo0BZlK" crossorigin="anonymous"></script>
    <script type="text/javascript">
        const imageInput = document.getElementById("id_banner");
        const imagePreview = document.getElementById("image_preview")

        imageInput.addEventListener("change", function(event) {
            const file = event.target.files[0];


            if( file ){
                const reader = new FileReader();

                reader.onload = function(eve) {
                    imagePreview.src = eve.target.result;
                    imagePreview.style.display = "block";
                }

                reader.readAsDataURL(file);
            }
        })
    </script>
{% endblock  %}

dashboard/templates/dashboard/phones/list.html
{% extends "dashboard/navpane.html" %}
{% block title %}Phone List{% endblock  %}
{% block content %}

    {{ block.super }}

    <div class="bg-white border border-3 border-grey py-4 px-4 mt-5 col-md-8" style="border-radius: 50px">
        <div class="d-flex justify-content-between my-5">
            <h1 class="h2">Our Phones</h1>
            <button class="btn rounded btn-color"><a class="text-decoration-none text-black fw-bold" href={% url "dashboard:insert_phone" %}>New Phone <i class="fa-solid fa-plus"></i></a></button>
        </div>
        <div class="border border-2 border-grey overflow-hidden" style="border-radius: 10px">
            <table class="table table-hover table-borderless">
                <thead class="table-secondary">
                    <tr>
                        <th class="fw-normal">Brand</th>
                        <th class="fw-normal">Model</th>
                        <th class="fw-normal">Ram/Storage</th>
                        <th class="fw-normal">Stock</th>
                        <th class="fw-normal">Color</th>
                        <th class="fw-normal">Price</th>
                        <th class="fw-normal">Action</th>
                    </tr>
                </thead>
                <tbody class="">
                    {% for phone in phones  %}
                        <tr class="">
                            <td>{{ phone.brand }}</td>
                            <td>{{ phone }}</td>
                            <td class="text-uppercase">{{ phone.ram }} / {{ phone.storage }}</td>
                            <td>{{ phone.instock }}</td>
                            <td>{{ phone.color }}</td>
                            <td>{{ phone.price }} MMK</td>
                            <td class="">
                                <a href="update/{{ phone }}"><i class="fa-solid fa-pen-to-square text-secondary"></i></a>
                                <a href="delete/{{ phone }}"><i class="fa-solid fa-trash text-secondary"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock  %}

dashboard/templates/dashboard/phones/update_form.html
{% extends "dashboard/navpane.html" %}
{% load static %}
{% block title %}Update Phone{% endblock  %}
{% block content %}

    {{ block.super }}

    <div class="bg-white border border-3 border-grey my-5 px-5 py-3 col-auto" style="border-radius:20px">
        <a class="text-dark btn text-decoration-none mt-3 mb-5" href={% url "dashboard:get_phone" %}><i class="fa-solid fa-arrow-left"></i> Back</a>

        <div class="container vw-100">
            
            <div class="row">

                <form action="" method="POST" enctype="multipart/form-data" class="col-md-8">
                    <div class="border border-3 border-grey p-4 mb-2" style="border-radius:20px">
                        <h1 class="h2 mb-5">Add Phone and Specifications</h1>
                        {% csrf_token %}
                        {% for each in form %}
                            <div class="form-group mb-3">
                                <label for={{each.id_for_label}} class="form-label" >{{ each.label }}</label>
                                {{ each }}
                            </div>
                        {% endfor %}
                    </div>
                    <button class="btn btn-color w-100 fw-bold py-4" type="Submit" >Update Product</button>
                </form>
                <div class="col-auto border border-5 border-dark overflow-hidden" style="width:200px; height: 300px">
                    {% if form.instance.banner %}
                        <img id="image_preview" src="{{ form.instance.banner.url }}" alt="{{ form.instance.model_name }}" class="w-100 h-100" style="object-fit:contain">
                    {% else %}
                        <img id="image_preview" src={% static "img/fallback.png" %} class="w-100 h-100" style="object-fit:contain" alt="No image available">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <!-- Boostrap CDN JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js" integrity="sha384-7qAoOXltbVP82dhxHAUje59V5r2YsVfBafyUDxEdApLPmcdhBPg1DKg1ERo0BZlK" crossorigin="anonymous"></script>
    <script type="text/javascript">
        const imageInput = document.getElementById("id_banner");
        const imagePreview = document.getElementById("image_preview")

        imageInput.addEventListener("change", function(event) {
            const file = event.target.files[0];


            if( file ){
                const reader = new FileReader();

                reader.onload = function(eve) {
                    imagePreview.src = eve.target.result;
                    imagePreview.style.display = "block";
                }

                reader.readAsDataURL(file);
            }
        })
    </script>
{% endblock %}